# Your solution
version: '3'
services:

  book_catalog:
    image: book_catalog:1
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://projectweek07_0au9_user:0nhCxA4I8nxFuYvtu9mGiRELGtGLEWfn@dpg-crjou9o8fa8c73f7vop0-a.oregon-postgres.render.com/projectweek07_0au9
    restart: "no"

  inventory_management:
    image: inventory_management:1
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://projectweek07_0au9_user:0nhCxA4I8nxFuYvtu9mGiRELGtGLEWfn@dpg-crjou9o8fa8c73f7vop0-a.oregon-postgres.render.com/projectweek07_0au9   
    restart: "no"
